apiVersion: v1
kind: Namespace
metadata:
  name: mlflow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-data
  namespace: mlflow
spec:
  storageClassName: accordion-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: mlflow
  labels:
    app: mlflow-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
        - name: mlflow-server
          image: registry.accordions.co.kr/mlflow-server:ysmoon
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000
          volumeMounts:
            - name: mlflow-data
              mountPath: /mlflow
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              cpu: '1'
              memory: 2Gi
            limits:
              cpu: '2'
              memory: 4Gi
      volumes:
        - name: mlflow-data
          persistentVolumeClaim:
            claimName: mlflow-data
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-server
  namespace: mlflow
spec:
  type: NodePort
  selector:
    app: mlflow-server
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30500
